# rag_chain.py

import re
import openai

from .prompts import SYSTEM_PROMPT
from .retrieval import PolicyRetriever
from .utils import (
    LLM_MODEL,
    OPENROUTER_API_KEY,
    SEED,
)


class PolicyRAG:
    """
    End-to-end Retrieval-Augmented Generation (RAG) pipeline.

    Workflow:
        User Question
              ↓
        Retrieve Context
              ↓
        Build Prompt
              ↓
        Query LLM
              ↓
        Return Response
    """

    def __init__(self):
        """Initializes the retriever and OpenRouter client."""

        if (
            not OPENROUTER_API_KEY
            or OPENROUTER_API_KEY == "API_KEY"
        ):
            raise ValueError(
                "Please replace the placeholder 'API_KEY' "
                "with your actual OpenRouter API key "
                "inside your .env file."
            )

        self.retriever = PolicyRetriever()

        self.client = openai.OpenAI(
            base_url="https://openrouter.ai/api/v1",
            api_key=OPENROUTER_API_KEY,
        )

    def retrieve_context(self, question: str):
        """
        Retrieves relevant policy documents.
        """

        documents = self.retriever.retrieve_context(question)

        if not documents:
            return None

        return documents

    def build_prompt(
        self,
        question: str,
        context: str,
    ):
        """
        Builds the user prompt using the retrieved context.
        """

        return (
            "--- START RETRIEVED POLICY CONTEXT ---\n"
            f"{context}\n"
            "--- END RETRIEVED POLICY CONTEXT ---\n\n"
            f"Employee Question: {question}\n"
            "Answer:"
        )

    def generate(self, question: str):
        """
        Executes the complete RAG pipeline.
        """

        documents = self.retrieve_context(question)

        if not documents:
            return {
                "answer": (
                    "I can only answer about our policies within the available company policy documents."
                ),
                "sources": [],
            }

        context = self.retriever.format_context(documents)

        prompt = self.build_prompt(
            question,
            context,
        )

        # try:
        #     print("\n" + "=" * 80)
        #     print(prompt)
        #     print("=" * 80 + "\n")
            
        #     response = self.client.chat.completions.create(
        #         model=LLM_MODEL,
        #         messages=[
        #             {
        #                 "role": "system",
        #                 "content": SYSTEM_PROMPT,
        #             },
        #             {
        #                 "role": "user",
        #                 "content": prompt,
        #             },
        #         ],
        #         temperature=0.0,
        #         seed=SEED,
        #     )

        #     if isinstance(response, str):
        #         return {
        #             "answer": (
        #                 "OpenRouter returned an unexpected response:\n"
        #                 f"{response}"
        #             ),
        #             "sources": [],
        #         }

        #     answer = response.choices[0].message.content
            
        #     # --- 🛠️ POST-PROCESSING & SOURCE CITATION FILTERING ---
            
        #     # 1. Instantly suppress sources if the LLM defaults to its out-of-scope refusal message
        #     fallback_phrases = ["i can only answer", "not present in the indexed corpus", "available company policy"]
        #     if any(phrase in answer.lower() for phrase in fallback_phrases):
        #         return {
        #             "answer": answer,
        #             "sources": []
        #         }

        #     # 2. Extract explicit bracket citations generated by the LLM (e.g. [policy.md])
        #     citations = re.findall(r'\[([^\]]+)\]', answer)
        #     citations_clean = [c.strip().lower() for c in citations]

        #     seen = set()
        #     sources = []

        #     for doc in documents:
        #         source_name = doc.metadata.get("source", "Unknown Document")
                
        #         # Verify if this precise file snippet was referenced in the final generated text
        #         clean_filename = source_name.lower()
        #         is_cited = any(cit in clean_filename for cit in citations_clean) or (len(documents) == 1)
                
        #         if not is_cited:
        #             continue  # Ignore background noise chunks not used to build the answer

        #         snippet = doc.page_content.strip()
        #         if len(snippet) > 300:
        #             snippet = snippet[:300].rsplit(" ", 1)[0] + "..."

        #         headers = []
        #         for level in ("Header 1", "Header 2", "Header 3", "Header 4"):
        #             if level in doc.metadata:
        #                 headers.append(doc.metadata[level])

        #         section = " > ".join(headers) if headers else "General Section"

        #         # Deduplicate by document + section combination
        #         dup_key = (source_name, section)
        #         if dup_key not in seen:
        #             seen.add(dup_key)
        #             sources.append(
        #                 {
        #                     "source": source_name,
        #                     "section": section,
        #                     "snippet": snippet,
        #                 }
        #             )

        #     return {
        #         "answer": answer,
        #         "sources": sources,
        #     }

        # except Exception as e:
        #     return {
        #         "answer": (
        #             "Pipeline connection error via OpenRouter API:\n"
        #             f"{e}"
        #         ),
        #         "sources": [],
        #     }

        try:
            print("\n" + "=" * 80)
            print(prompt)
            print("=" * 80 + "\n")
            
            # Formulate the payload with specific required OpenRouter tracking headers
            response = self.client.chat.completions.create(
                model=LLM_MODEL,
                messages=[
                    {
                        "role": "system",
                        "content": SYSTEM_PROMPT,
                    },
                    {
                        "role": "user",
                        "content": prompt,
                    },
                ],
                temperature=0.0,
                seed=SEED,
                extra_headers={
                    "HTTP-Referer": "http://localhost:8501", # Mandated by OpenRouter free tiers
                    "X-Title": "NileTech Policy Assistant",   # Mandated by OpenRouter free tiers
                }
            )

            # Safety Guard: Intercept Cloudflare/Clerk HTML strings coming from OpenRouter's platform wrapper
            if not response or not hasattr(response, 'choices') or len(response.choices) == 0:
                return {
                    "answer": "⚠️ OpenRouter returned an invalid or empty server object. Please verify your API key access status on openrouter.ai.",
                    "sources": [],
                }

            answer = response.choices[0].message.content
            
            # If OpenRouter accidentally feeds an HTML string directly into the choices payload text
            if str(answer).strip().startswith("<!DOCTYPE html") or "clerk.openrouter.ai" in str(answer):
                return {
                    "answer": "🔒 **Authentication Challenge Error**: OpenRouter is blocking this request with an account challenge screen. Please check your OpenRouter dashboard settings or swap out your API key.",
                    "sources": []
                }
            
            # --- POST-PROCESSING & SOURCE CITATION FILTERING ---
            fallback_phrases = ["i can only answer", "not present in the indexed corpus", "available company policy"]
            if any(phrase in answer.lower() for phrase in fallback_phrases):
                return {
                    "answer": answer,
                    "sources": []
                }

            citations = re.findall(r'\[([^\]]+)\]', answer)
            citations_clean = [c.strip().lower() for c in citations]

            seen = set()
            sources = []

            for doc in documents:
                source_name = doc.metadata.get("source", "Unknown Document")
                clean_filename = source_name.lower()
                is_cited = any(cit in clean_filename for cit in citations_clean) or (len(documents) == 1)
                
                if not is_cited:
                    continue  

                snippet = doc.page_content.strip()
                if len(snippet) > 300:
                    snippet = snippet[:300].rsplit(" ", 1)[0] + "..."

                headers = []
                for level in ("Header 1", "Header 2", "Header 3", "Header 4"):
                    if level in doc.metadata:
                        headers.append(doc.metadata[level])

                section = " > ".join(headers) if headers else "General Section"

                dup_key = (source_name, section)
                if dup_key not in seen:
                    seen.add(dup_key)
                    sources.append(
                        {
                            "source": source_name,
                            "section": section,
                            "snippet": snippet,
                        }
                    )

            return {
                "answer": answer,
                "sources": sources,
            }

        except Exception as e:
            # Handle situations where the library throws errors directly when reading non-JSON text
            err_msg = str(e)
            if "<!DOCTYPE html" in err_msg or "clerk.openrouter" in err_msg:
                return {
                    "answer": "🔒 **API Authentication Failed**: OpenRouter redirected your request to an external login portal. Make sure your newly generated API Key is set inside your `.env` configurations.",
                    "sources": []
                }
            return {
                "answer": f"Pipeline connection error via OpenRouter API:\n\n{err_msg}",
                "sources": [],
            }
